name: Build .NET Projects

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore "XV2 Xml Serializer.sln"

      - name: Build Debug (Any CPU)
        run: dotnet build "XV2 Xml Serializer.sln" --configuration Debug --no-restore

      - name: Build Release (Any CPU)
        run: dotnet build "XV2 Xml Serializer.sln" --configuration Release --no-restore

      - name: Upload Debug binaries
        uses: actions/upload-artifact@v4
        with:
          name: debug-binaries
          path: |
            **/bin/Debug/**

      - name: Upload Release binaries
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: |
            **/bin/Release/**
